### ISSUE TITLE
Fail to deserialize model: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by lizzzcai** [coreweave/tensorizer#90]
I am trying out tensorizer and I can serialize the model using `hf_serialization.py`. However, when I try to deserialize the model using `deserialize.py` from `local path`, I am getting error: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`. 

The model I am testing is `"EleutherAI/gpt-neo-125M"`, the same error for `"EleutherAI/gpt-j-6B"`

error:
```
root@nginx:/workspace/tensorizer/examples# python3 deserialize_local.py
Deserialized 327.9 MB in 0.12s, 2.6 GB/s
Memory usage before: CPU: (maxrss: 985MiB F: 22,761MiB) GPU: (U: 256MiB F: 22,467MiB T: 22,723MiB) TORCH: (R: 0MiB/0MiB, A: 0MiB/0MiB)
Memory usage after: CPU: (maxrss: 1,141MiB F: 22,757MiB) GPU: (U: 606MiB F: 22,117MiB T: 22,723MiB) TORCH: (R: 330MiB/330MiB, A: 319MiB/319MiB)
Traceback (most recent call last):
  File "/workspace/tensorizer/examples/deserialize_local.py", line 67, in <module>
    output = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1525, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2622, in sample
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 975, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 843, in forward
    outputs = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 570, in forward
    attn_outputs = self.attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 522, in forward
    return self.attention(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 283, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 237, in _attn
    attn_weights = torch.where(causal_mask, attn_weights, mask_value)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

tensorizer: `2.8.1`
transformers: `4.37.2`
torch: `2.1.2`
accelerate: `0.26.1`
machine type: `g5.2xlarge`

nivida-smi:
```
root@nginx:/workspace/tensorizer/examples# nvidia-smi
Mon Feb 26 03:01:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    Off | 00000000:00:1E.0 Off |                    0 |
|  0%   29C    P8              16W / 300W |      2MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

I also try out `"mistralai/Mistral-7B-Instruct-v0.1"` which I got a different error: `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

Let me know if anything needed, thanks.

**Comment by Eta0** [comment]
Thank you for the bug report! I put up a change that should fix this issue here: #91.

This was caused by non-persistent buffers appearing on the CPU device instead of CUDA. Non-persistent buffers on a module are not touched during deserialization via `deserializer.load_into_module(model)`, so they were remaining on the CPU while everything else was loaded to CUDA. The change adds an extra `model = model.to(device)` so that any remaining non-persistent buffers are moved to a device matching the deserializer's device.

**Comment by Eta0** [comment]
@lizzzcai as it turns out, it can be! I re-did the code around this in #96 to be more effective, initializing the weights on the intended device from the start rather than copying them there. This should be the most efficient method possible.

**Comment by 9654msharm-dotcom** [comment]
a28ffc1c1833542b495cd1a7dd49507a12f50c12🇮🇳 hello 👋
